### ISSUE TITLE
Create a Recorder

### ISSUE THREAD

**Issue by LeeCampbell** [HdrHistogram/HdrHistogram.NET#11]
Consider supporting Recorder (which supports multiple concurrent writers), but that will also require a ConcurrentHistogram.

Question: _What is the Recorder?_

**Comment by mattwarren** [comment]
> Question: What is the Recorder?

I think he means [Recorder.java](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/Recorder.java) and the specialist implementations such as [SingleWriterRecorder.java](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/SingleWriterRecorder.java) and [DoubleRecorder.java](https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/DoubleRecorder.java)

**Comment by giltene** [comment]
You can see a good pattern for using a Recorder (along with a log writer) in jHiccup: https://github.com/giltene/jHiccup/blob/master/src/main/java/org/jhiccup/HiccupMeter.java#L626

SingleWriterRecorder is probably the most common use case, and the fastest in code. Recorder supports multiple writer threads, which is less commonly needed. DoubleRecorder will only be needed once you port DoubleHistogram.
