### ISSUE TITLE
Create CI build

### ISSUE THREAD

**Issue by LeeCampbell** [HdrHistogram/HdrHistogram.NET#2]
Create an automated build that 
 1. compiles the code for each platform
 2. runs all the tests
 3. packages and deploys

Consider using AppVeyor?

**Comment by mattwarren** [comment]
I agree with using AppVeyor, I actually had HdrHistogram.NET building on it previously (before I broke the build), see https://ci.appveyor.com/project/mattwarren/hdrhistogram-net

**Comment by LeeCampbell** [comment]
Closed by #20 
Using AppVeyor. Was very easy to set up. Impressed.

Added badges (build status) to home page, and also feedback to Pull Requests.
