### ISSUE TITLE
Create documentation standards

### ISSUE THREAD

**Issue by LeeCampbell** [HdrHistogram/HdrHistogram.NET#3]
Adoption of a library can be greatly improved with quality documentation.

Providing guidelines on how to create consistent documentation can reduce rework and improve the feeling of a quality repository.

example of a set of guidelines : http://dotnet.github.io/orleans/Documentation-Guidelines

**Comment by mattwarren** [comment]
Yeah it's a good point, previously I just copied over the Java doc comments, but they don't work the same as the .NET ones, so it was a bit messy.

**Comment by LeeCampbell** [comment]
Wiki updated with contribution guidelines.
Code largely has the text from the Java code base, with improvements/adjustments made where applicable
